In [1]:
import numpy as np
import tensorflow as tf

## Excercise on Basic Tensor Operations

In [2]:
# Create a 1D uint8 Numpy array comprising of first 25 natural numbers
x = np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [3]:
# Convert numpy array to Tensor using tf.constant
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [4]:
# Square the input tensor
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [5]:
# Reshape the tensor into 5*5 matrix
x = tf.reshape(x, shape=(5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

In [7]:
# Cast tensor x into float32
x = tf.cast(x, dtype=tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [8]:
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
# Multiply tensor x and y
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [10]:
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [11]:
# Add tensor x and y
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

#### The shape parameter for tf.constant

In [12]:
x = tf.constant([1, 2, 3, 4], shape=(2, 2))
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### The shape parameter for tf.Variable

In [13]:
try:
  x = tf.Variable([1, 2, 3, 4], shape=(2, 2))
except ValueError as v:
  print(v)

In this `tf.Variable` creation, the initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).


In [15]:
x = tf.Variable([1, 2, 3, 4])
x = tf.reshape(x, shape=(2, 2))
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [18]:
# The shape parameter for 'tf.Variable' is used to give the tensor
# a less specific shape than the shape of the initial value. Setting
# the shape like below example will set the shape of of the Tensor
# to be 'unknown'. The variable can then be updated with an array 
# of any shape

vector = tf.Variable([1, 2, 3, 4], shape=tf.TensorShape(None))
vector

<tf.Variable 'Variable:0' shape=<unknown> dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

## Other Tensorflow Operations

In [16]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [19]:
mammal = tf.Variable('Elephant', dtype=tf.string)
mammal

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>

In [20]:
tensor = tf.constant(-1.0, shape=(2, 3))
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>